/**
 * EditorWysywigMceModule Worker — Unit Tests
 *
 * TDD seed: tests generated by `quanti create`.
 * Run with: npm run test
 *
 * Rules (TESTING_STANDARDS.md):
 *   - Test public API surface (black-box)
 *   - Mock only external calls (D1, R2, fetch)
 *   - min 2 sad paths per happy path
 */

import { describe, it, expect } from 'vitest';

describe('EditorWysywigMceModule Worker', () => {
    // ── Contract: module identity ──────────────────────────────────────────────
    it('should export the correct module name', async () => {
        // Import the definition to validate the contract
        const { editor_wysywig_mceDefinition } = await import('../definition.js');
        expect(editor_wysywig_mceDefinition.id).toBe('editor-wysywig-mce');
        expect(editor_wysywig_mceDefinition.version).toBeDefined();
        expect(editor_wysywig_mceDefinition.schemaVersion).toBeGreaterThanOrEqual(1);
    });

    // ── Sad path: missing projectId ───────────────────────────────────────────
    it('should reject operations without projectId', async () => {
        // Validates that the contract enforces tenant isolation
        const { ListPayloadSchema } = await import('../contract.js');
        const result = ListPayloadSchema.safeParse({});
        expect(result.success).toBe(false);
    });

    // ── Sad path: invalid id format ───────────────────────────────────────────
    it('should reject getById with non-UUID id', async () => {
        const { GetByIdPayloadSchema } = await import('../contract.js');
        const result = GetByIdPayloadSchema.safeParse({ projectId: 1, id: 'not-a-uuid' });
        expect(result.success).toBe(false);
    });
});
